name: Automatic Release

on:
  push:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v3
      with: 
        submodules: recursive
    - name: Setup git
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
    - name: Install toolchain
      run: |
        sudo apt install graphicsmagick-imagemagick-compat mtools lbzip2 curl bison flex gcc g++ unzip dosfstools automake build-essential nasm qemu-utils gdisk git -y
        git clone https://github.com/TheUltimateFoxOS/FoxOS --recurse
        cd FoxOS
        bash tools/toolchain.sh
        make all install_sdk
    - name: build
      run: bash build.sh
    - uses:  marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: "latest"
        prerelease: false
        title: "Development Build"
        files: | 
            pkgs/*.elf