name: Automatic Release

on:
  push:
    branches: [ main ]
    
  workflow_dispatch:
  repository_dispatch:

jobs:
  build:
    runs-on: [ubuntu-latest]
    container:
      image: ghcr.io/theultimatefoxos/foxos-toolchain:latest

    steps:
    - uses: actions/checkout@v3
      with: 
        submodules: recursive
    - name: Setup git
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
    - name: install sudo
      run: |
        apt update
        apt install sudo -y
    - name: Install toolchain
      run: |
        git clone https://github.com/TheUltimateFoxOS/FoxOS --recurse
        cd FoxOS
        make all install_sdk
    - name: install build tools
      run: apt install nodejs python3 -y
    - name: build
      run: bash build_packets.sh
    - uses:  marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: "latest"
        prerelease: false
        title: "Development Build"
        files: | 
            pkgs/*.elf
